"""init

Revision ID: a8ac09e2d4a2
Revises: 
Create Date: 2023-04-20 17:30:37.513605

"""
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a8ac09e2d4a2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "demo",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_by_name", sa.String(), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=True),
        sa.Column("updated_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("updated_by_name", sa.String(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.Column("deleted_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("deleted_by_name", sa.String(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_demo_created_at"), "demo", ["created_at"], unique=False)
    op.create_index(op.f("ix_demo_deleted"), "demo", ["deleted"], unique=False)
    op.create_index(op.f("ix_demo_deleted_at"), "demo", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_demo_updated_at"), "demo", ["updated_at"], unique=False)
    op.create_table(
        "teams",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_by_name", sa.String(), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=True),
        sa.Column("updated_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("updated_by_name", sa.String(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.Column("deleted_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("deleted_by_name", sa.String(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("headquarters", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_created_at"), "teams", ["created_at"], unique=False)
    op.create_index(op.f("ix_teams_deleted"), "teams", ["deleted"], unique=False)
    op.create_index(op.f("ix_teams_deleted_at"), "teams", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_teams_name"), "teams", ["name"], unique=False)
    op.create_index(op.f("ix_teams_updated_at"), "teams", ["updated_at"], unique=False)
    op.create_table(
        "heroes",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_by_name", sa.String(), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=True),
        sa.Column("updated_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("updated_by_name", sa.String(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.Column("deleted_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("deleted_by_name", sa.String(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("secret_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("team_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_heroes_age"), "heroes", ["age"], unique=False)
    op.create_index(
        op.f("ix_heroes_created_at"), "heroes", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_heroes_deleted"), "heroes", ["deleted"], unique=False)
    op.create_index(
        op.f("ix_heroes_deleted_at"), "heroes", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_heroes_name"), "heroes", ["name"], unique=False)
    op.create_index(
        op.f("ix_heroes_updated_at"), "heroes", ["updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_heroes_updated_at"), table_name="heroes")
    op.drop_index(op.f("ix_heroes_name"), table_name="heroes")
    op.drop_index(op.f("ix_heroes_deleted_at"), table_name="heroes")
    op.drop_index(op.f("ix_heroes_deleted"), table_name="heroes")
    op.drop_index(op.f("ix_heroes_created_at"), table_name="heroes")
    op.drop_index(op.f("ix_heroes_age"), table_name="heroes")
    op.drop_table("heroes")
    op.drop_index(op.f("ix_teams_updated_at"), table_name="teams")
    op.drop_index(op.f("ix_teams_name"), table_name="teams")
    op.drop_index(op.f("ix_teams_deleted_at"), table_name="teams")
    op.drop_index(op.f("ix_teams_deleted"), table_name="teams")
    op.drop_index(op.f("ix_teams_created_at"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_demo_updated_at"), table_name="demo")
    op.drop_index(op.f("ix_demo_deleted_at"), table_name="demo")
    op.drop_index(op.f("ix_demo_deleted"), table_name="demo")
    op.drop_index(op.f("ix_demo_created_at"), table_name="demo")
    op.drop_table("demo")
    # ### end Alembic commands ###
